Repository tmaxsoft-us/oftools_compile, pull requests merged in 2022-04, with the labels that each got.

#14 🐛✅RM#6590-10: Bugfix special characters filename
  oftools_compile/Job.py
  tests/unit/test_job/__init__.py
  tests/unit/test_job/asm.prof
  tests/unit/test_job/sources/#sample.asm
  tests/unit/test_job/sources/$sample.asm
  tests/unit/test_job/sources/@sample.asm
  tests/unit/test_job/test_job_file_name.py
Labels: bug

#17 ✨🐛RM#6597: Handle KeyboardInterrupt exception
  bin/oftools_compile
  oftools_compile/Clear.py
  oftools_compile/Log.py
  oftools_compile/Main.py
  oftools_compile/enums/ErrorEnum.py
  oftools_compile/enums/LogEnum.py
  tests/unit/main/test_keyboard_input.py
Labels: bug, enhancement

#18 Feature Workdir and Source
  oftools_compile/Clear.py
  oftools_compile/Context.py
  oftools_compile/Grouping.py
  oftools_compile/Main.py
  oftools_compile/SetupJob.py
  oftools_compile/Source.py
  oftools_compile/enums/LogEnum.py
  tests/unit/source/sources/directories.txt
  tests/unit/source/sources/files.txt
  tests/unit/source/sources/skip.txt
  tests/unit/source/test_analyze.py
Labels: bug, enhancement

#19 ✨✅RM#5057-42: Backup and housekeeping testing
  oftools_compile/Profile.py
  oftools_compile/SetupJob.py
  oftools_compile/enums/ErrorEnum.py
  oftools_compile/enums/LogEnum.py
  oftools_compile/handlers/FileHandler.py
  tests/unit/setup_job/profiles/backup.prof
  tests/unit/setup_job/profiles/backup_empty.prof
  tests/unit/setup_job/profiles/backup_value_error.prof
  tests/unit/setup_job/profiles/housekeeping_30_days.prof
  tests/unit/setup_job/profiles/housekeeping_empty.prof
  tests/unit/setup_job/profiles/housekeeping_missing_backup.prof
  tests/unit/setup_job/profiles/housekeeping_value_error.prof
  tests/unit/setup_job/test_analyze.py
  tests/unit/setup_job/test_process_backup.py
  tests/unit/setup_job/test_process_housekeeping.py
Labels: enhancement

#20 🎨♻️RM#6595-1: Grouping and clear logic rework
  oftools_compile/Clear.py
  oftools_compile/Context.py
  oftools_compile/Grouping.py
  oftools_compile/JobFactory.py
  oftools_compile/Main.py
  oftools_compile/Profile.py
  oftools_compile/Report.py
  oftools_compile/SetupJob.py
  oftools_compile/enums/LogEnum.py
Labels: enhancement
